# Site
name: "Memoirs"
title: "Memoirs"
description: "I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: ""
google_analytics: "UA-169886569-1"
disqus: "demowebsite"
# mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
mailchimp-list: "https://app.us10.list-manage.com/subscribe/post?u=4de247e978cab0e1532f96492&amp;id=a636da9c44"
include: ["_pages"]
permalink: /:title/
email: gmwamwaja@outlook.com

# Build settings
theme: minima

# Authors
authors:
  gwamaka:
    name: Gwamaka
    display_name: Gwamaka
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: gmwamwaja@outlook.com
    web: https://gwamakacharles.netlify.app
    twitter: https://twitter.com/wowthemesnet
    description: "A programmer and loves basketball."
  john:
    name: John
    display_name: John
    avatar: "assets/images/avatar.png"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://gwamakacharles.netlify.app
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-paginate
  - jekyll-sitemap

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
